# The URL the site will be built for
base_url = "https://markwilkinson.tech"
theme = "hermit_zola"
title = "Mark Wilkinson"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

taxonomies = [
           {name = "tags", rss = true}
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
#highlight_code = false



[extra]
# Put all your custom variables here

home_subtitle = "Aspiring Cybersecurity Professional"

footer_copyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

hermit_menu = [
    { link = "/posts", name = "Posts" },
    { link = "/about", name = "About" }
]

hermit_social = [
    { name = "mastodon", link = "https://infosec.exchange/@markwilk" },
    { name = "linkedin", link = "https://www.linkedin.com/in/mrk-wilkinson/" },
    { name = "github", link = "https://github.com/mrk-wilkinson" },
    { name = "email", link = "mailto:mark@markwilkinson.tech" }
]



[extra.highlightjs]
enable = true
clipboard = true
theme = "vs2015"

[extra.disqus]
enable = false
# Take this from your Disqus account
shortname = "my-supa-dupa-blog"

[extra.author]
name = "Mark Wilkinson"
email = "mark@markwilkinson.tech"

[extra.google_analytics]
enable = false
id = "UA-4XXXXXXX-X"
